language: cpp
dist: trusty

os: linux

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7

compiler:
  - gcc

script:
  - export CC=gcc-7
  - export CXX=g++-7
  - make -j 3 test
