LIB = ../lib
BIN = ../bin

# TODO: in the future include all the tools from the data analysis module

all: python_tools

python_tools:
	@chmod +x generate_xml_file.py
	@cp generate_xml_file.py $(BIN)/generate_xml_file.py

clean:
	$(RM) $(BIN)/generate_xml_file.py

